// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiwD0vlmfbMtPE8-Xp60vq6xdN3xfXF2U',
    appId: '1:1080471545714:web:0ad0de634d7fd37f669feb',
    messagingSenderId: '1080471545714',
    projectId: 'apk-kekeibo',
    authDomain: 'apk-kekeibo.firebaseapp.com',
    storageBucket: 'apk-kekeibo.firebasestorage.app',
    measurementId: 'G-P1LGKTRD1Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAamQlwKdIuAc-Gc46Bv_pxnuLbT6Qqa9M',
    appId: '1:1080471545714:android:55643705fd734a91669feb',
    messagingSenderId: '1080471545714',
    projectId: 'apk-kekeibo',
    storageBucket: 'apk-kekeibo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWGMGkarudjoBZi9goS7XsBI4JZSQer7I',
    appId: '1:1080471545714:ios:650574388c1a50c9669feb',
    messagingSenderId: '1080471545714',
    projectId: 'apk-kekeibo',
    storageBucket: 'apk-kekeibo.firebasestorage.app',
    iosBundleId: 'com.example.apkKakeibo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWGMGkarudjoBZi9goS7XsBI4JZSQer7I',
    appId: '1:1080471545714:ios:650574388c1a50c9669feb',
    messagingSenderId: '1080471545714',
    projectId: 'apk-kekeibo',
    storageBucket: 'apk-kekeibo.firebasestorage.app',
    iosBundleId: 'com.example.apkKakeibo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiwD0vlmfbMtPE8-Xp60vq6xdN3xfXF2U',
    appId: '1:1080471545714:web:ad2f726a74f535ff669feb',
    messagingSenderId: '1080471545714',
    projectId: 'apk-kekeibo',
    authDomain: 'apk-kekeibo.firebaseapp.com',
    storageBucket: 'apk-kekeibo.firebasestorage.app',
    measurementId: 'G-BYBWLN31CS',
  );
}
